#! /usr/bin/env bash
# ws- entry point
# Author: Mikhail Medvedev <mmedvede@cs.uml.edu>
VERSION=0.1.3-1

set -e
set -u

usage(){
  __commands(){
    #http://stackoverflow.com/questions/948008/linux-command-to-list-all-available-commands-and-aliases
    __all_commands_full_paths(){
      echo -n $PATH | xargs -d : -I {} find {} -name $(basename $0)-* -maxdepth 1 \
        -executable -type f
    }
  desc_var="__short_description"
  for command in $(__all_commands_full_paths)
  do
    echo -en "    $(<<< $command sed s/.*$(basename $0)-// |sort -u )\t" 
    desc=$(grep -m1 "$desc_var=" $command || true)
    <<< $desc sed -e 's/'$desc_var'="\(.*\)"/\1/' 
  done
  }
  cat 1>&2 << EOF
Workspace management tools
Usage: $(basename $0) [-v] | [COMMAND] [-h]

  -v  Print version number

  COMMAND:
$(__commands)

  If COMMAND is not listed above, ws runs 'rosws COMMAND' instead.
  ws with no arguments defaults to 'rosws info --untracked'.
  Some commands support bash tab completion.
EOF
}

while getopts "vh" OPTION
do
  case $OPTION in
    v)
      echo "$(basename $0) version $VERSION"
      exit 0
      ;;
    h|?)
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))


if [ -z "$*" ]; then
  rosws info --untracked
else
  # if ws-$* does not exist, pass to rosws
  hash ws-$* 2>/dev/null || rosws $* 
  hash ws-$* 2>/dev/null && ws-$* 
fi
