#! /usr/bin/env bash
# Switch the current workspace.
# Regenerates ~/.roswsrc based on selected workspace.
# author: Mikahil Medvedev <mmedvede@cs.uml.edu>

set -e
set -u

# This has to be in sync with the one ws-save uses
POSTFIX="-workspace"
DEPTH=4

find ~ -maxdepth $DEPTH -wholename *$POSTFIX/initialize | sed -e "s/\/[^\/]*$POSTFIX.*//g"
