#! /usr/bin/env bash
# Switch the current workspace.
# Regenerates ~/.roswsrc based on selected workspace.
# author: Mikahil Medvedev <mmedvede@cs.uml.edu>

set -e
set -u

# This has to be in sync with the one ws-save uses
POSTFIX="-workspace"

WSRC=.roswsrc
WSRC_PATH=~/$WSRC
ENV_FILE=~/ros_env.sh

usage(){
  __short_description="Sets current workspace"
  cat 1>&2 << EOF
$__short_description

Usage: $(basename $0) [<WORKSPACE>] [-h]

  -h  Print this help message.

If workspace is ommitted, assume working directory is a desired 
  workspace.

EOF
}

while getopts "h" OPTION
do
  case $OPTION in
    h|?)
      usage
      exit 1
      ;;
  esac
done


if [ -z "$*" ]; then
  # Case for no arguments
  dir=$(pwd)
else
  dir=$1
fi
if [ -d "$dir" ]; then 
  # Expand relative paths
  dir=$(cd $dir && pwd)
else
  echo "$dir is not a directory." 1>&2
  exit 1
fi
initialize_script=$dir/$(basename $dir)$POSTFIX/initialize

# Check for setup.bash
if [ ! -e "$dir/setup.bash" ]; then
  echo "Error: No setup.bash at '$dir'" 1>&2
  exit 1
fi

generate_for_unsupported(){
  # The workspace/initialize script does not have a function to generate config files
  # Use the fallback defaults
  echo "Warn: $(basename $dir) is not supported version, generating default $WSRC and $ENV_FILE" 1>&2
  echo "(Over)writing $WSRC_PATH"
  ws_generate_workspace_rc $dir> $WSRC_PATH
  echo "(Over)writing $ENV_FILE"
  ws_generate_env_loader > $ENV_FILE && chmod +x $ENV_FILE
}


if [ ! -f "$initialize_script" ]; then
  echo "No $initialize_script found" 1>&2
  generate_for_unsupported
else
  if [ -n "$(grep "initialize-generate-workspace-rc" $initialize_script)" -a \
    -n "$(grep "initialize-generate-env-loader" $initialize_script)" ]; then
    echo "(Over)writing $WSRC_PATH"
    $initialize_script generate-workspace-rc > $WSRC_PATH 
    echo "(Over)writing $ENV_FILE"
    $initialize_script generate-env-loader > $ENV_FILE
  else
    echo "$initialize_script is old version" 1>&2
    generate_for_unsupported
  fi
fi

echo "
  ## Switched to $(basename $dir)
  ## to use it:
  source $WSRC_PATH"
