#! /usr/bin/env bash
# Switch the current workspace.
# Regenerates ~/.roswsrc based on selected workspace.
# author: Mikahil Medvedev <mmedvede@cs.uml.edu>

set -e
set -u

# This has to be in sync with the one ws-save uses
POSTFIX="-workspace"

WSRC=.roswsrc
WSRC_PATH=~/$WSRC
ENV_FILE=~/ros_env.sh

usage(){
  __short_description="Sets current workspace"
  cat 1>&2 << EOF
$__short_description

Usage: $(basename $0) [<WORKSPACE>] [-h]

  -h  Print this help message.

If workspace is ommitted, assume working directory is a desired 
  workspace.

EOF
}

while getopts "h" OPTION
do
  case $OPTION in
    h|?)
      usage
      exit 1
      ;;
  esac
done


if [ -z "$*" ]; then
  # Case for no arguments
  dir=$(pwd)
else
  dir=$1
fi
if [ -d "$dir" ]; then 
  # Expand relative paths
  dir=$(cd $dir && pwd)
else
  echo "$dir is not a directory." 1>&2
  exit 1
fi
initialize_script=$dir/$(basename $dir)$POSTFIX/initialize
if [ ! -f "$initialize_script" ]; then
  echo "$dir is not a supported workspace, no $initialize_script found" 1>&2
  exit 1
fi
if [ -n "$(grep "initialize-generate-workspace-rc" $initialize_script)" -a \
  -n "$(grep "initialize-generate-env-loader" $initialize_script)" ]; then
  $initialize_script generate-workspace-rc > $WSRC_PATH 
  $initialize_script generate-env-loader > $ENV_FILE
  echo "(Over)writing $WSRC_PATH
(Over)writing $ENV_FILE
  Successfully switched to $(basename $dir).
  Source $WSRC to use the selected workspace."
else
  echo "$initialize_script is not a correct version." 1>&2
  exit 1
fi
